"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 15:33:57.818730
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector, for text-chunk embeddings in Phase 4. Versioned here with the schema.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ufcstats_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ufcstats_id"),
    )
    op.create_index(op.f("ix_events_event_date"), "events", ["event_date"], unique=False)
    op.create_table(
        "fighters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ufcstats_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("height_cm", sa.Double(), nullable=True),
        sa.Column("reach_cm", sa.Double(), nullable=True),
        sa.Column("stance", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ufcstats_id"),
    )
    op.create_table(
        "load_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rows_read", sa.Integer(), nullable=True),
        sa.Column("rows_loaded", sa.Integer(), nullable=True),
        sa.Column("rows_rejected", sa.Integer(), nullable=True),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fighter_aliases",
        sa.Column("alias_norm", sa.Text(), nullable=False),
        sa.Column("fighter_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fighter_id"],
            ["fighters.id"],
        ),
        sa.PrimaryKeyConstraint("alias_norm"),
    )
    op.create_table(
        "fights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ufcstats_id", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("fighter_a_id", sa.Integer(), nullable=False),
        sa.Column("fighter_b_id", sa.Integer(), nullable=False),
        sa.Column("red_fighter_id", sa.Integer(), nullable=True),
        sa.Column("weight_class", sa.Text(), nullable=False),
        sa.Column("gender", sa.String(length=1), nullable=False),
        sa.Column("is_title_fight", sa.Boolean(), nullable=False),
        sa.Column("scheduled_rounds", sa.SmallInteger(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("decision_type", sa.Text(), nullable=True),
        sa.Column("method_detail", sa.Text(), nullable=True),
        sa.Column("finish_round", sa.SmallInteger(), nullable=True),
        sa.Column("finish_time_sec", sa.Integer(), nullable=True),
        sa.Column("referee", sa.Text(), nullable=True),
        sa.Column("has_round_stats", sa.Boolean(), nullable=False),
        sa.CheckConstraint("(outcome = 'win') = (winner_id IS NOT NULL)", name="win_has_winner"),
        sa.CheckConstraint(
            "decision_type IS NULL OR decision_type IN ('unanimous', 'split', 'majority')",
            name="decision_type_values",
        ),
        sa.CheckConstraint("gender IN ('M', 'F')", name="gender_values"),
        sa.CheckConstraint(
            "method IN ('decision', 'ko_tko', 'submission', 'dq', 'other')", name="method_values"
        ),
        sa.CheckConstraint(
            "outcome IN ('win', 'draw', 'no_contest', 'unknown')", name="outcome_values"
        ),
        sa.CheckConstraint("fighter_a_id < fighter_b_id", name="neutral_fighter_order"),
        sa.CheckConstraint(
            "red_fighter_id IS NULL OR red_fighter_id IN (fighter_a_id, fighter_b_id)",
            name="red_is_a_participant",
        ),
        sa.CheckConstraint(
            "winner_id IS NULL OR winner_id IN (fighter_a_id, fighter_b_id)",
            name="winner_is_a_participant",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter_a_id"],
            ["fighters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter_b_id"],
            ["fighters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["red_fighter_id"],
            ["fighters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["fighters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ufcstats_id"),
    )
    op.create_index(op.f("ix_fights_event_id"), "fights", ["event_id"], unique=False)
    op.create_index(op.f("ix_fights_fighter_a_id"), "fights", ["fighter_a_id"], unique=False)
    op.create_index(op.f("ix_fights_fighter_b_id"), "fights", ["fighter_b_id"], unique=False)
    op.create_table(
        "rankings",
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("ranking_type", sa.Text(), nullable=False),
        sa.Column("weight_class", sa.Text(), nullable=False),
        sa.Column("name_raw", sa.Text(), nullable=False),
        sa.Column("fighter_id", sa.Integer(), nullable=True),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint(
            "ranking_type IN ('division', 'pound_for_pound')", name="ranking_type_values"
        ),
        sa.CheckConstraint("rank >= 0", name="rank_non_negative"),
        sa.ForeignKeyConstraint(
            ["fighter_id"],
            ["fighters.id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_date", "ranking_type", "weight_class", "name_raw"),
    )
    op.create_index(
        "ix_rankings_fighter_snapshot", "rankings", ["fighter_id", "snapshot_date"], unique=False
    )
    op.create_table(
        "fight_round_stats",
        sa.Column("fight_id", sa.Integer(), nullable=False),
        sa.Column("fighter_id", sa.Integer(), nullable=False),
        sa.Column("round", sa.SmallInteger(), nullable=False),
        sa.Column("head_landed", sa.SmallInteger(), nullable=True),
        sa.Column("head_att", sa.SmallInteger(), nullable=True),
        sa.Column("body_landed", sa.SmallInteger(), nullable=True),
        sa.Column("body_att", sa.SmallInteger(), nullable=True),
        sa.Column("leg_landed", sa.SmallInteger(), nullable=True),
        sa.Column("leg_att", sa.SmallInteger(), nullable=True),
        sa.Column("distance_landed", sa.SmallInteger(), nullable=True),
        sa.Column("distance_att", sa.SmallInteger(), nullable=True),
        sa.Column("clinch_landed", sa.SmallInteger(), nullable=True),
        sa.Column("clinch_att", sa.SmallInteger(), nullable=True),
        sa.Column("ground_landed", sa.SmallInteger(), nullable=True),
        sa.Column("ground_att", sa.SmallInteger(), nullable=True),
        sa.Column("knockdowns", sa.SmallInteger(), nullable=True),
        sa.Column("sig_strikes_landed", sa.SmallInteger(), nullable=True),
        sa.Column("sig_strikes_att", sa.SmallInteger(), nullable=True),
        sa.Column("total_strikes_landed", sa.SmallInteger(), nullable=True),
        sa.Column("total_strikes_att", sa.SmallInteger(), nullable=True),
        sa.Column("takedowns_landed", sa.SmallInteger(), nullable=True),
        sa.Column("takedowns_att", sa.SmallInteger(), nullable=True),
        sa.Column("submission_att", sa.SmallInteger(), nullable=True),
        sa.Column("reversals", sa.SmallInteger(), nullable=True),
        sa.Column("ctrl_sec", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint("round BETWEEN 1 AND 5", name="round_range"),
        sa.ForeignKeyConstraint(
            ["fight_id"],
            ["fights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter_id"],
            ["fighters.id"],
        ),
        sa.PrimaryKeyConstraint("fight_id", "fighter_id", "round"),
    )
    op.create_table(
        "fight_totals",
        sa.Column("fight_id", sa.Integer(), nullable=False),
        sa.Column("fighter_id", sa.Integer(), nullable=False),
        sa.Column("knockdowns", sa.SmallInteger(), nullable=True),
        sa.Column("sig_strikes_landed", sa.SmallInteger(), nullable=True),
        sa.Column("sig_strikes_att", sa.SmallInteger(), nullable=True),
        sa.Column("total_strikes_landed", sa.SmallInteger(), nullable=True),
        sa.Column("total_strikes_att", sa.SmallInteger(), nullable=True),
        sa.Column("takedowns_landed", sa.SmallInteger(), nullable=True),
        sa.Column("takedowns_att", sa.SmallInteger(), nullable=True),
        sa.Column("submission_att", sa.SmallInteger(), nullable=True),
        sa.Column("reversals", sa.SmallInteger(), nullable=True),
        sa.Column("ctrl_sec", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fight_id"],
            ["fights.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fighter_id"],
            ["fighters.id"],
        ),
        sa.PrimaryKeyConstraint("fight_id", "fighter_id"),
    )
    op.create_table(
        "odds",
        sa.Column("fight_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_detail", sa.Text(), nullable=True),
        sa.Column("decimal_odds_a", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("decimal_odds_b", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("source IN ('mdabbert', 'silver')", name="odds_source_values"),
        sa.CheckConstraint(
            "decimal_odds_a > 1 AND decimal_odds_b > 1", name="decimal_odds_greater_than_one"
        ),
        sa.ForeignKeyConstraint(
            ["fight_id"],
            ["fights.id"],
        ),
        sa.PrimaryKeyConstraint("fight_id", "source"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("odds")
    op.drop_table("fight_totals")
    op.drop_table("fight_round_stats")
    op.drop_index("ix_rankings_fighter_snapshot", table_name="rankings")
    op.drop_table("rankings")
    op.drop_index(op.f("ix_fights_fighter_b_id"), table_name="fights")
    op.drop_index(op.f("ix_fights_fighter_a_id"), table_name="fights")
    op.drop_index(op.f("ix_fights_event_id"), table_name="fights")
    op.drop_table("fights")
    op.drop_table("fighter_aliases")
    op.drop_table("load_runs")
    op.drop_table("fighters")
    op.drop_index(op.f("ix_events_event_date"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
